# backend.http
# @import ./auth.http
# @ref loggedGerente
# @ref loggedRecepcionista
# @ref loggedCliente

@baseUrl=http://localhost:3000/api/v1

### CREATE Paquete Turístico
POST {{baseUrl}}/paquetes-turisticos
Content-Type: application/json
Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
# Authorization: Bearer {{loggedCliente.data.token}}

{
  "nombre": "Aventura Total Salinas",
  "ubicacion": "Jujuy",
  "descripcion": "Tour completo por las salinas.",
  "duracionEnDias": 3,
  "precioBase": 1234.56
}

### CREATE Vacante
POST {{baseUrl}}/vacantes
Content-Type: application/json
Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
# Authorization: Bearer {{loggedCliente.data.token}}

{
  "paqueteTuristicoId": 1,
  "fechaDeSalida": "2026-08-15",
  "cupoTotal": 10
}

### CREATE Reserva
POST {{baseUrl}}/reservas
Content-Type: application/json
# Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
Authorization: Bearer {{loggedCliente.data.token}}

{
    "clienteId": 1,
    "vacanteId": 1,
    "fechaDeReservacion": "2026-08-15",
    "cantidadDePersonas": 3
}

### CONFIRMAR Reserva (Genera un Comprobante de Reserva)
PUT {{baseUrl}}/reservas/checkout/1
Content-Type: application/json
# Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
Authorization: Bearer {{loggedCliente.data.token}}

{
    "montoPagado": 3703.68
}

### CREATE Pago (Manual) (también genera un comprobante de Reserva)
POST {{baseUrl}}/pagos
Content-Type: application/json
Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
# Authorization: Bearer {{loggedCliente.data.token}}

{
  "reservaId": 1,
  "monto": 3703.68,
  "metodoPago": "TARJETA_CREDITO"
}

### CANCELAR Reserva
PUT {{baseUrl}}/reservas/cancel/1
Content-Type: application/json
# Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
Authorization: Bearer {{loggedCliente.data.token}}

### GET ALL OWN (cliente) Comprobantes
GET {{baseUrl}}/comprobantes/me
Content-Type: application/json
# Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
Authorization: Bearer {{loggedCliente.data.token}}

### DOWNLOAD Comprobante en PDF
GET {{baseUrl}}/comprobantes/1/download-pdf
Content-Type: application/json
# Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
Authorization: Bearer {{loggedCliente.data.token}}
