# pagos.http
@baseUrl=http://localhost:3000/api/v1/pagos
# @import ./auth.http
# @ref loggedGerente
# @ref loggedRecepcionista
# @ref loggedCliente

### CheckoutSession Pago
POST {{baseUrl}}/checkout-session
Content-Type: application/json
Authorization: Bearer {{loggedGerente.token}}
# Authorization: Bearer {{loggedRecepcionista.token}}
# Authorization: Bearer {{loggedCliente.token}}

{
    "reservaId": 1
}

### Complete Pago
POST {{baseUrl}}/webhook
Content-Type: application/json
Authorization: Bearer {{loggedGerente.token}}
# Authorization: Bearer {{loggedRecepcionista.token}}
# Authorization: Bearer {{loggedCliente.token}}

{
    "reservaId": 1,
    "monto": 2469.12,
    "metodoPago": "TARJETA_DEBITO"
}

### Get Pagos (Gerente y Recepcionista)
GET {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{loggedGerente.token}}
# Authorization: Bearer {{loggedRecepcionista.token}}
# Authorization: Bearer {{loggedCliente.token}}

### Create Pago (Gerente y Recepcionista)
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{loggedGerente.token}}
# Authorization: Bearer {{loggedRecepcionista.token}}
# Authorization: Bearer {{loggedCliente.token}}

{
  "reservaId": 1,
  "monto": 3703.68,
  "metodoPago": "TARJETA_CREDITO"
}

### Get Pago By ID (Gerente y Recepcionista)
GET {{baseUrl}}/1
Content-Type: application/json
# Authorization: Bearer {{loggedGerente.token}}
Authorization: Bearer {{loggedRecepcionista.token}}
# Authorization: Bearer {{loggedCliente.token}}

### Edit Pago (Gerente y Recepcionista)
PUT {{baseUrl}}/1
Content-Type: application/json
# Authorization: Bearer {{loggedGerente.token}}
Authorization: Bearer {{loggedRecepcionista.token}}
# Authorization: Bearer {{loggedCliente.token}}

{
    "monto": 4000,
    "metodoPago": "TRANSFERENCIA"
}

### Delete Pago (Gerente y Recepcionista)
DELETE {{baseUrl}}/1
Content-Type: application/json
Authorization: Bearer {{loggedGerente.token}}
# Authorization: Bearer {{loggedRecepcionista.token}}
# Authorization: Bearer {{loggedCliente.token}}
