# usuarios.http
@baseUrl=http://localhost:3000/api/v1/usuarios
# @import ./auth.http
# @ref loggedGerente
# @ref loggedRecepcionista
# @ref loggedCliente

### Get Usuarios
GET {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
# Authorization: Bearer {{loggedCliente.data.token}}

### Create Usuario (gerente)
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
# Authorization: Bearer {{loggedCliente.data.token}}

{
    "correoElectronico": "gerente@company.com",
    "contraseña": "gerente-pass",
    "legajo": "EMP-0001",
    "sede": "central",
    "esGerente": true
}

### Create Usuario (recepcionista)
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
# Authorization: Bearer {{loggedCliente.data.token}}

{
    "correoElectronico": "recepcionista@company.com",
    "contraseña": "recepcionista-pass",
    "legajo": "EMP-0002",
    "sede": "sucursal"
}
### Create Usuario (cliente)

POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
# Authorization: Bearer {{loggedCliente.data.token}}

{
    "correoElectronico": "cliente@world.com",
    "contraseña": "cliente-pass",
    "dni": "0000001",
    "nombreCompleto": "Xenon Air",
    "telefono": "555-000-1234"
}

### Get Usuario By ID
GET {{baseUrl}}/3
Content-Type: application/json
Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
# Authorization: Bearer {{loggedCliente.data.token}}

### Edit Usuario
PUT {{baseUrl}}/3
Content-Type: application/json
Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
# Authorization: Bearer {{loggedCliente.data.token}}

{
    "contraseña": "cliente-pass-1"
}

### Delete Usuario
DELETE {{baseUrl}}/2
Content-Type: application/json
Authorization: Bearer {{loggedGerente.data.token}}
# Authorization: Bearer {{loggedRecepcionista.data.token}}
# Authorization: Bearer {{loggedCliente.data.token}}
